### ISSUE TITLE
Forking for a different kind of project

### ISSUE THREAD

**Issue by arthurysong** [VinDuv/switch-arduino-controller#1]
hey Vinduv, I'm trying to make a custom switch controller using an arduino (by controller I don't mean like a bot, I mean the actual controller you hold in your hand to input buttons and controls into the switch).

Were you able to get your arduino bot working with the switch? If you could that means I could use this method to make a simple custom arduino-switch controller right??

**Comment by VinDuv** [comment]
Hi! Thanks for your interest in this project.

To answer your question, I have used of my project on a real Switch and it actually works, without issues. (Though I haven't used it for quite a while now so I hope it has not been broken by a Switch software update...)

If you want to use my project, you can write an "automation" code that will poll the state of the buttons/axis and send it to the USB interface handler, in a loop. Note however that this will introduce a latency. Not a problem for automation, but a bit more for a real controller...

If you can use another microcontroller, I'd suggest the Teensy 2.0++ (or any microcontroller supported by LUFA). Its avantage over the Arduino Uno is that the same microcontroller can communicate over USB and read/write the I/O pins (on the Arduino is is the task of two different microcontrollers). You can use [this code](https://github.com/VinDuv/switch-arduino-controller/blob/master/src/usb-iface/standalone-usb-iface.c), modifying it to get the state of real buttons/axis in `refresh_and_send_controller_data` instead of using a static `report_data` table.

Don't hesitate to ask if you have more questions.

**Comment by arthurysong** [comment]
Hey Vinduv,

Thanks for getting back to me. That's super cool how you got the bot
working!

I'll definitely look into getting the Teensy controller instead of the
arduino uno for it's io pins. I think though first I need to understand how
to program using C xP. (So far I only have experience using the Arduino
IDE.)

I plan on starting this project maybe a month from now, so I'll hit you up
if/when I run into any problems. Thanks again for your help!

Arthur
