### ISSUE TITLE
Code fails to compile

### ISSUE THREAD

**Issue by MatthewCerza** [VinDuv/switch-arduino-controller#2]
Hello VinDuv, I'm trying to use this library with an Arduino UNO R3 to make a physical controller connected to an Arduino that can communicate with the Switch. Before trying to modify the swsh.c file to take input instead of perform automated tasks I decided I wanted to try and compile the code into the .hex files like you stated in the readme but I get this error. Do you have any insight?

avr-gcc -mmcu=atmega328p -flto -fuse-linker-plugin -Wl,--gc-sections -o src/swsh.elf src/swsh/swsh.o src/lib/automation.o src/lib/automation-utils.o src/lib/user-io.o
/usr/local/opt/avr-binutils/bin/avr-ld: /var/folders/zb/bwstvvb94t92w5mkj5wxg3hr0000gn/T//swsh.elf.yK8ICC.ltrans0.ltrans.o: in function `move_in_circles':
<artificial>:(.text+0xbb2): undefined reference to `pause_automation'
/usr/local/opt/avr-binutils/bin/avr-ld: /var/folders/zb/bwstvvb94t92w5mkj5wxg3hr0000gn/T//swsh.elf.yK8ICC.ltrans0.ltrans.o: in function `go_to_nursery_helper':
<artificial>:(.text+0xc2c): undefined reference to `pause_automation'
/usr/local/opt/avr-binutils/bin/avr-ld: /var/folders/zb/bwstvvb94t92w5mkj5wxg3hr0000gn/T//swsh.elf.yK8ICC.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup+0x128): undefined reference to `pause_automation'
/usr/local/opt/avr-binutils/bin/avr-ld: <artificial>:(.text.startup+0x260): undefined reference to `pause_automation'
/usr/local/opt/avr-binutils/bin/avr-ld: <artificial>:(.text.startup+0x3ae): undefined reference to `pause_automation'
collect2: error: ld returned 1 exit status
make: *** [src/swsh.elf] Error 1

Thank you!

**Comment by VinDuv** [comment]
Hi!
Hmm, `pause_automation` is defined inline in `src/lib/automation.h`, but apparently in you case it wasn’t inlined properly, resulting in a link error.
Which AVR toolchain are you using? I tried on macOS with CrossPack-AVR-20131216 and on Debian Stable with `gcc-avr 1:5.4.0+Atmel3.6.2-1+b1`/`avr-libc 1:2.0.0+Atmel3.6.2-1.1` and it builds fine.

EDIT: Can you also `git pull`, try running `make clean swsh.hex` and check that no compiler warnings appear before the link error?

**Comment by MatthewCerza** [comment]
I fixed the compilation issue, It's a "hacky" fix but I moved the pause_automation method in full to wherever it was defined. I'm facing another issue through, I'm trying to use your code to make a physical Nintendo Switch controller with an Arduino and when passing through analog readings from an analog stick the Arduino's TX and RX Led's flash 2 or 3 times. What could those error codes mean? I have the inputs from the analog stick scaled down from 0 to 255.

**Comment by MatthewCerza** [comment]
I have a line in swsh.c like this:
**send_update(BT_NONE, DP_NEUTRAL, S_COORD((int)l_potXScaled, (int)l_potYScaled), S_NEUTRAL);**

l_potXScaled and l_potYScaled are values between 0 and 255. 
Unless I follow up the update IMMEDIATLEY with 

**send_update(BT_NONE, DP_NEUTRAL, S_NEUTRAL, S_NEUTRAL);** 

Both the TX and RX leds flash twice. Even if I just put a delay statement in between them, it panics.

I need to be able to remove the "send neutral" statement because with that in use, the controller acts like it it rapidly being centered and then pushed in a certain direction instead of being held. Any idea why it's panicking?

**Comment by VinDuv** [comment]
Two blinks on the TX/RX LEDs means that `src/usb-iface/usb-iface.c` called `panic(2)`, which means either [invalid data received](https://github.com/VinDuv/switch-arduino-controller/blob/master/src/usb-iface/usb-iface.c#L207) or [no message received from the main µC](https://github.com/VinDuv/switch-arduino-controller/blob/master/src/usb-iface/usb-iface.c#L216) (I should have put separate codes…). I suspect it’s the second one in your case.

The important thing is that you don’t need delay calls in your code. You should call `send_update` as fast as you can. If the USB µC has not processed the previous message, `send_update` will automatically wait.

In your case, your code should probably do something like this:
```c
init_automation();
for (;;) {
  <determine the current inputs>
  send_update(<current inputs>);
}
```

When plugged on the Switch, the USB µC needs new data at a rate of 125 Hz (Switch USB poll rate) / 5 = 25 Hz, or once very 40 ms. `send_update` also takes some time to send the data, probably something like 10 ms. So as long as your code manages to take less than 30 ms between calls to `send_update`, you should be fine.

If you suspect your code needs more time between `send_update` calls, you can change the cycle count of the USB µC : https://github.com/VinDuv/switch-arduino-controller/blob/master/src/usb-iface/usb-iface.c#L162
If you change the 5 to a 10, the USB µC will repeat each message 10 times instead of 5, so it will request new data half as frequently.

**Comment by MatthewCerza** [comment]
Thank you so so much! That was the issue, my code is working perfectly now.
