### ISSUE TITLE
Motion Controls

### ISSUE THREAD

**Issue by dhenry437** [VinDuv/switch-arduino-controller#6]
Is it possible to emulate motion controls as well?

**Comment by VinDuv** [comment]
Not easily, unfortunately.

This project emulates a Hoki Pokken controller, which is a basic HID controller without motion controls.
The Pro Controller is more difficult to emulate because it has specific features that the Switch it’s connected to will attempt to use (for instance, reading the controller body and grip colors, settings the four LEDs, etc). If they are not emulated correctly the controller will not work.

I have found some previous work emulating the Pro controller, most notably [this thread](https://gimx.fr/forum/viewtopic.php?t=2216) which led to [this repository](https://github.com/AterialDawn/Nintendo-Switch-Pro-Controller-AVR-Firmware). Unfortunately, it apparently doesn’t work anymore. Fixing it would require having a way to capture USB packets, which I don’t have.

I will gladly accept patches implementing it, though :)
